# Storing personal details in variables
name = "Muhammad Faizan Khan"
slack_username = "Faizan"
email = "faizanjeee@hotmail.com"
hobby = "Learning Bioinformatics Skills"
countries = "Pakistan"
discipline = "Biomedical Sciences"
preferred_language = "Python"

# Printing the organized output in a readable way
print("User Information:")
print("Name:", name)
print("Slack Username:", slack_username)
print("Email:", email)
print("Hobby:", hobby)
print("Countries:", countries)
print("Discipline:", discipline)
print("Preferred Programming Language:", preferred_language)
